export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SIGN_OUT = "SIGN_OUT";

export const GET_USER ="GET_USER"

export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED= "GET_MOVIES_FAILED"
export const GET_MOVIES_ID= "GET_MOVIES_ID"
export const GET_MOVIES_REVIEW= "GET_MOVIES_REVIEW"

