export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED= "GET_MOVIES_FAILED"